from .UserSchema import *
from .DoctorSchema import *
from .MedicineSchema import *
from .DiagnosisSchema import *
from .IllnessSchema import *
from .ReviewSchema import *
from .NotificationSchema import *
from .ScheduleSchema import *
from .OrderSchema import *
from .MessageSchema import *
from .HospitalSchema import *
from .PatientSchema import *
